from fpdf import FPDF
import datetime

class PDFReport(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.set_margins(15, 15, 15) # Increased margins

    def header(self):
        # Header Background
        self.set_fill_color(0, 51, 102) # Share India Blue
        self.rect(0, 0, 210, 40, 'F')
        
        # Logo
        try:
            # Load logo, resize to fit nicely
            self.image('data/share_india_logo.png', 15, 12, 40) 
        except Exception as e:
            print(f"Warning: Logo not found: {e}")
        
        # Title
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(255, 255, 255) # White
        self.set_xy(70, 15)
        self.cell(0, 10, 'Personalized Insurance Plan', 0, 0, 'R')
        
        # Subtitle
        self.set_font('Helvetica', '', 10)
        self.set_xy(70, 25)
        self.cell(0, 10, 'Tailored recommendations for your financial security', 0, 0, 'R')
        
        self.ln(35) # Move below header area

    def footer(self):
        self.set_y(-20)
        # Decorative line
        self.set_draw_color(200, 200, 200)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(5)
        
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(100, 100, 100) # Gray
        self.cell(0, 5, f'Generated by Share India InsureBot | Page {self.page_no()}', 0, 0, 'C')
        self.ln(4)
        # Footer Link Logic
        text1 = "Visit "
        text2 = "shareindiainsurance.com"
        text3 = " used for investment opportunities."
        url = "https://shareindiainsurance.com/"
        
        self.set_font('Helvetica', 'I', 8)
        w1 = self.get_string_width(text1)
        w2 = self.get_string_width(text2)
        w3 = self.get_string_width(text3)
        
        total_width = w1 + w2 + w3
        start_x = (self.w - total_width) / 2
        
        self.set_x(start_x)
        self.set_text_color(100, 100, 100) # Gray
        self.cell(w1, 5, text1, 0, 0, 'L')
        
        self.set_text_color(0, 0, 255) # Blue
        self.cell(w2, 5, text2, 0, 0, 'L', link=url)
        
        self.set_text_color(100, 100, 100) # Gray
        self.cell(w3, 5, text3, 0, 0, 'L')

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(0, 51, 102) # Share India Blue
        self.cell(0, 10, title.upper(), 0, 1, 'L')
        # Underline
        self.set_draw_color(229, 9, 20) # Accent Red (approx)
        self.set_line_width(1)
        self.line(self.get_x(), self.get_y(), self.get_x() + 40, self.get_y()) # Short underscore
        self.ln(8)

    def chapter_body_card(self, content_dict):
        """Creates a card-like layout for key-value pairs"""
        self.set_font('Helvetica', '', 10)
        
        # Box background
        start_y = self.get_y()
        self.set_fill_color(248, 249, 250) # Very light gray
        self.set_draw_color(230, 230, 230)
        self.set_line_width(0.2)
        
        # Calculate height needed
        line_height = 8
        count = len(content_dict)
        height = (count * line_height) + 10
        self.rect(15, start_y, 180, height, 'DF')
        
        self.set_xy(20, start_y + 5)
        
        for k, v in content_dict.items():
            self.set_x(20)
            self.set_font('Helvetica', 'B', 10)
            self.set_text_color(80, 80, 80)
            self.cell(50, line_height, f"{k}:", 0, 0)
            
            self.set_font('Helvetica', '', 10)
            self.set_text_color(0, 0, 0)
            self.cell(0, line_height, f"{v}", 0, 1)

        self.ln(10)

    def section_highlight(self, title, body):
        self.set_fill_color(230, 240, 255) # Light Blue
        self.rect(15, self.get_y(), 180, 8, 'F')
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(0, 51, 102)
        self.cell(180, 8, f"  {title}", 0, 1)
        self.ln(2)
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, body)
        self.ln(6)

    def add_client_details(self, profile):
        self.chapter_title("Client Profile")
        
        details = {
            "Full Name": profile.get('name', 'Valued Client'),
            "Age": f"{int(float(profile.get('age', 0)))} years" if profile.get('age') else "N/A",
            "Annual Income": f"Rs. {int(float(profile.get('income', 0)))}" if profile.get('income') else "N/A",
            "Location": profile.get('city', 'Not Specified'),
            "Occupation": profile.get('occupation', 'Not Specified'),
            "Education": profile.get('education', 'Not Specified'),
            "Gender": profile.get('gender', 'N/A').title()
        }
        self.chapter_body_card(details)

    def add_recommendation(self, recommendation):
        self.chapter_title("Recommended Plan")
        
        if not recommendation:
            self.set_font('Helvetica', 'I', 11)
            self.cell(0, 10, "No specific recommendation generated.", 0, 1)
            return

        # Main Plan Card
        self.set_fill_color(255, 255, 255)
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.5)
        
        # Product Title
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(0, 51, 102)
        self.cell(0, 10, recommendation.get('product_name', 'Insurance Plan'), 0, 1)
        self.ln(2)
        
        # Plan Details Grid
        details = {
            "Insurer": recommendation.get('company', 'N/A'),
            "Sum Assured": recommendation.get('sum_assured', 'N/A'),
            "Premium (Est.)": f"Rs. {recommendation.get('premium_estimate', 'N/A')} / year",
            "Claim Settlement Ratio": f"{recommendation.get('csr', 'N/A')}%"
        }
        self.chapter_body_card(details)
        
        # Why this fits you - Modern Box
        suitability = recommendation.get('suitability_reason', "This plan matches your profile requirements.")
        self.section_highlight("Why this fits you", suitability)
        
        # USP / Features
        usp = recommendation.get('usp', 'Comprehensive coverage.')
        detailed_features = recommendation.get('features', {})
        
        feature_text = f"{usp}\n\n"
        
        if detailed_features:
            for k, v in detailed_features.items():
                if k == 'description': continue
                if isinstance(v, dict):
                     feature_text += f"- {k}:\n  {' '.join([f'{sk}: {sv}' for sk, sv in v.items()])}\n\n"
                else:
                     feature_text += f"- {k}:\n  {v}\n\n"
                     
        self.section_highlight("Key Features & Additional Benefits", feature_text.strip())

def generate_client_report(profile, recommendation, output_path="client_report.pdf"):
    pdf = PDFReport()
    pdf.add_page()
    
    # Date at top right relative to content start
    pdf.set_y(45)
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f"Date: {datetime.date.today().strftime('%d %B %Y')}", 0, 1, 'R')
    pdf.ln(5)

    pdf.add_client_details(profile)
    pdf.add_recommendation(recommendation)
    
    pdf.output(output_path)
    return output_path
